# Generated by Django 5.2.1 on 2025-05-10 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos_app', '0002_initial'),
        ('pedidos_app', '0001_initial'),
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios_app.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos_app.estadopedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos_app.metodopago'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos_app.pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos_app.tipoentrega'),
        ),
        migrations.AddField(
            model_name='pedidoprocesadopor',
            name='bodeguero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_preparados', to='usuarios_app.personal'),
        ),
        migrations.AddField(
            model_name='pedidoprocesadopor',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_vendidos', to='usuarios_app.personal'),
        ),
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together={('pedido', 'producto')},
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha'], name='pedidos_fecha_6a1dae_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', 'fecha'], name='pedidos_cliente_9e0f42_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado_pedido'], name='pedidos_estado__8956b6_idx'),
        ),
    ]
