# Generated by Django 5.2.1 on 2025-05-14 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geografia_app', '0001_initial'),
        ('pedidos_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comuna_envio',
            field=models.ForeignKey(blank=True, help_text='Comuna de envío', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_enviados_aqui', to='geografia_app.comuna'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.CharField(blank=True, help_text='Dirección de envío completa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email_contacto',
            field=models.EmailField(blank=True, help_text='Email de contacto para el pedido', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_completo_contacto',
            field=models.CharField(blank=True, help_text='Nombre completo para el contacto del pedido', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono_contacto',
            field=models.CharField(blank=True, help_text='Teléfono de contacto para el pedido', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
