# Generated by Django 5.2.1 on 2025-05-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_app', '0003_pedido_comuna_envio_pedido_direccion_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='webpay_token',
            field=models.CharField(blank=True, help_text='Token de la transacción de Webpay', max_length=255, null=True),
        ),
    ]
