# Generated by Django 5.2.1 on 2025-05-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_app', '0004_pedido_webpay_token'),
        ('sucursales_app', '0002_bodega_direccion_bodega_tipo_bodega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal a la que se asocia este pedido (para ventas, gestión, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_originados_en_sucursal', to='sucursales_app.sucursal'),
        ),
    ]
