# Generated by Django 5.2.1 on 2025-05-10 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos_app', '0001_initial'),
        ('sucursales_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cambiada', models.IntegerField(help_text='Positivo para entrada, negativo para salida')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursales_app.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos_app.producto')),
            ],
            options={
                'verbose_name': 'Historial de Stock',
                'verbose_name_plural': 'Historiales de Stock',
                'db_table': 'historial_stock',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='historial_s_fecha_dae0bf_idx'), models.Index(fields=['producto', 'bodega', 'fecha'], name='historial_s_product_4183b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales_app.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos_app.producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'indexes': [models.Index(fields=['fecha_actualizacion'], name='inventario_fecha_a_26992f_idx')],
                'unique_together': {('producto', 'bodega')},
            },
        ),
    ]
