# Generated by Django 5.2.1 on 2025-05-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de Transacción',
                'verbose_name_plural': 'Estados de Transacciones',
                'db_table': 'estado_transaccion',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_pago', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='RegistroContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_contable', models.DateField(help_text='Fecha del asiento contable')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro Contable',
                'verbose_name_plural': 'Registros Contables',
                'db_table': 'registro_contable',
                'ordering': ['-fecha_contable', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta_ultimos_digitos', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos')),
                ('marca_tarjeta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca de tarjeta')),
                ('fecha_expiracion', models.DateField()),
                ('token_pasarela', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Token de pasarela')),
            ],
            options={
                'verbose_name': 'Tarjeta de Cliente (Referencia)',
                'verbose_name_plural': 'Tarjetas de Clientes (Referencias)',
                'db_table': 'tarjeta_cliente',
            },
        ),
        migrations.CreateModel(
            name='TransaccionTarjetaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaccion_pasarela', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Transacción Pasarela')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Transacción de Tarjeta Cliente',
                'verbose_name_plural': 'Transacciones de Tarjeta Cliente',
                'db_table': 'transacciones_tarjeta_cliente',
            },
        ),
    ]
