# Generated by Django 5.2.1 on 2025-05-10 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos_app', '0001_initial'),
        ('usuarios_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocontable',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarjetacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.cliente'),
        ),
        migrations.AddField(
            model_name='transacciontarjetacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios_app.cliente'),
        ),
        migrations.AddField(
            model_name='transacciontarjetacliente',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos_app.estadotransaccion'),
        ),
        migrations.AddField(
            model_name='transacciontarjetacliente',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos_app.metodopago'),
        ),
        migrations.AddField(
            model_name='transacciontarjetacliente',
            name='tarjeta_cliente_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos_app.tarjetacliente', verbose_name='Referencia Tarjeta'),
        ),
        migrations.AddField(
            model_name='registrocontable',
            name='transaccion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos_app.transacciontarjetacliente'),
        ),
        migrations.AddIndex(
            model_name='transacciontarjetacliente',
            index=models.Index(fields=['fecha_transaccion'], name='transaccion_fecha_t_0bb3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='transacciontarjetacliente',
            index=models.Index(fields=['cliente', 'fecha_transaccion'], name='transaccion_cliente_7c8b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocontable',
            index=models.Index(fields=['fecha_contable'], name='registro_co_fecha_c_c81442_idx'),
        ),
    ]
