# Generated by Django 5.2.1 on 2025-05-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocontable',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transacciontarjetacliente',
            name='monto_total',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
