# Generated by Django 5.2.1 on 2025-05-19 02:25

from django.db import migrations

def popular_datos_iniciales(apps, schema_editor):
    MetodoPago = apps.get_model('pagos_app', 'MetodoPago')
    EstadoTransaccion = apps.get_model('pagos_app', 'EstadoTransaccion')

    # Métodos de Pago
    MetodoPago.objects.get_or_create(descripcion_pago="Webpay")
    MetodoPago.objects.get_or_create(descripcion_pago="Transferencia Bancaria") # Ejemplo de otro

    # Estados de Transacción
    EstadoTransaccion.objects.get_or_create(nombre_estado="Pendiente de Pago")
    EstadoTransaccion.objects.get_or_create(nombre_estado="Pagado")
    EstadoTransaccion.objects.get_or_create(nombre_estado="Pago Fallido")
    EstadoTransaccion.objects.get_or_create(nombre_estado="Anulado")
    EstadoTransaccion.objects.get_or_create(nombre_estado="Reembolsado")



class Migration(migrations.Migration):

    dependencies = [
        ('pagos_app', '0003_alter_registrocontable_monto_and_more'),
    ]

    operations = [
        migrations.RunPython(popular_datos_iniciales),
    ]
