# Generated by Django 5.2.1 on 2025-05-19 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos_app', '0004_popular_datos_pago_inicial'),
        ('pedidos_app', '0004_pedido_webpay_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciontarjetacliente',
            name='codigo_autorizacion_pasarela',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Autorización Pasarela'),
        ),
        migrations.AddField(
            model_name='transacciontarjetacliente',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_pago', to='pedidos_app.pedido'),
        ),
        migrations.AddField(
            model_name='transacciontarjetacliente',
            name='ultimos_digitos_tarjeta',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos Dígitos Tarjeta'),
        ),
    ]
