# Generated by Django 5.2.1 on 2025-05-10 21:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_api', models.CharField(max_length=100, unique=True)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('metodo_http', models.CharField(default='GET', help_text='GET, POST, PUT, DELETE, etc.', max_length=10)),
                ('headers_json', models.JSONField(blank=True, help_text='Cabeceras HTTP como objeto JSON', null=True)),
                ('autenticacion_tipo', models.CharField(blank=True, help_text='Ej: Bearer, Basic, API_KEY', max_length=50, null=True)),
                ('autenticacion_credenciales_json', models.JSONField(blank=True, help_text='Credenciales de autenticación (manejar con cuidado)', null=True)),
                ('tipo_api', models.CharField(blank=True, help_text='Ej: REST, SOAP, GraphQL', max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la configuración de API está activa')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Fecha de creación del registro')),
            ],
            options={
                'verbose_name': 'Configuración de API Externa',
                'verbose_name_plural': 'Configuraciones de APIs Externas',
                'db_table': 'api_config',
                'indexes': [models.Index(fields=['fecha_registro'], name='api_config_fecha_r_3aa532_idx'), models.Index(fields=['activo', 'tipo_api'], name='api_config_activo_063c96_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApiIntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='Endpoint específico llamado', max_length=500)),
                ('metodo_http', models.CharField(help_text='Método HTTP (GET, POST, etc.)', max_length=10)),
                ('fecha_hora_llamada', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la llamada')),
                ('duracion_ms', models.IntegerField(blank=True, help_text='Duración de la llamada en milisegundos', null=True)),
                ('codigo_estado', models.IntegerField(blank=True, help_text='Código de estado HTTP de la respuesta', null=True)),
                ('request_data', models.JSONField(blank=True, help_text='Datos enviados en la solicitud (si aplica)', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Datos recibidos en la respuesta', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la llamada falló', null=True)),
                ('success', models.BooleanField(default=False, help_text='Indica si la llamada fue exitosa')),
                ('api_config', models.ForeignKey(blank=True, help_text='Configuración de API utilizada para esta llamada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='integraciones_app.apiconfig')),
            ],
            options={
                'verbose_name': 'Registro de Integración API',
                'verbose_name_plural': 'Registros de Integraciones API',
                'db_table': 'api_integration_log',
            },
        ),
    ]
