# Generated by Django 5.2.1 on 2025-05-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiIntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='Endpoint específico llamado', max_length=500)),
                ('metodo_http', models.CharField(help_text='Método HTTP (GET, POST, etc.)', max_length=10)),
                ('fecha_hora_llamada', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la llamada')),
                ('duracion_ms', models.IntegerField(blank=True, help_text='Duración de la llamada en milisegundos', null=True)),
                ('codigo_estado', models.IntegerField(blank=True, help_text='Código de estado HTTP de la respuesta', null=True)),
                ('request_data', models.JSONField(blank=True, help_text='Datos enviados en la solicitud (si aplica)', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Datos recibidos en la respuesta', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la llamada falló', null=True)),
                ('success', models.BooleanField(default=False, help_text='Indica si la llamada fue exitosa')),
                ('api_config', models.ForeignKey(blank=True, help_text='Configuración de API utilizada para esta llamada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='integraciones_app.apiconfig')),
            ],
            options={
                'verbose_name': 'Registro de Integración API',
                'verbose_name_plural': 'Registros de Integraciones API',
                'db_table': 'api_integration_log',
            },
        ),
    ]
