# Generated by Django 5.2.1 on 2025-05-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0003_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
