# Generated by Django 5.2.1 on 2025-05-10 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_origen', models.CharField(max_length=3)),
                ('moneda_destino', models.CharField(max_length=3)),
                ('tasa', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fecha_validez', models.DateField()),
                ('fuente', models.CharField(default='No especificada', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cambio',
                'verbose_name_plural': 'Tipos de Cambio',
                'db_table': 'tipo_cambio',
                'ordering': ['-fecha_validez', 'moneda_origen', 'moneda_destino'],
                'indexes': [models.Index(fields=['fecha_validez'], name='tipo_cambio_fecha_v_379b10_idx'), models.Index(fields=['moneda_origen', 'moneda_destino', 'fecha_validez'], name='tipo_cambio_moneda__61b223_idx')],
                'unique_together': {('moneda_origen', 'moneda_destino', 'fecha_validez', 'fuente')},
            },
        ),
        migrations.CreateModel(
            name='ConversionDivisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_origen', models.DecimalField(decimal_places=2, max_digits=18)),
                ('moneda_origen', models.CharField(help_text='Código ISO de la moneda de origen (ej. USD, CLP)', max_length=3)),
                ('monto_destino', models.DecimalField(decimal_places=2, max_digits=18)),
                ('moneda_destino', models.CharField(help_text='Código ISO de la moneda de destino (ej. USD, CLP)', max_length=3)),
                ('tasa_conversion_manual', models.DecimalField(blank=True, decimal_places=6, help_text='Tasa de conversión utilizada si no se usó un TipoCambio predefinido.', max_digits=18, null=True)),
                ('fecha_conversion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró la conversión.')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o nota adicional sobre la conversión.', null=True)),
                ('tipo_cambio_aplicado', models.ForeignKey(blank=True, help_text='Tipo de cambio utilizado para esta conversión, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas_app.tipocambio')),
            ],
            options={
                'verbose_name': 'Conversión de Divisa',
                'verbose_name_plural': 'Conversiones de Divisas',
                'db_table': 'conversion_divisa',
                'ordering': ['-fecha_conversion'],
                'indexes': [models.Index(fields=['fecha_conversion'], name='conversion__fecha_c_b504e9_idx'), models.Index(fields=['moneda_origen', 'moneda_destino'], name='conversion__moneda__e9bd81_idx')],
            },
        ),
    ]
