# Generated by Django 5.2.1 on 2025-05-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0004_usuario_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='TipoPersonal',
        ),
    ]
