# Generated by Django 5.2.1 on 2025-05-12 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0005_remove_personal_tipo_delete_tipopersonal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='nombre_completo',
        ),
    ]
