# Generated by Django 5.2.1 on 2025-05-20 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales_app', '0001_initial'),
        ('usuarios_app', '0006_remove_cliente_email_remove_cliente_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='bodega_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sucursales_app.bodega', verbose_name='Bodega Asignada'),
        ),
    ]
