# Generated by Django 5.2.1 on 2025-05-12 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes_app', '0001_initial'),
        ('productos_app', '0003_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_vendidos_en_informes', to='productos_app.producto'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='productos_afectados',
            field=models.ManyToManyField(blank=True, help_text='Productos a los que aplica esta promoción. Dejar vacío si aplica a toda la venta.', related_name='promociones_asociadas', to='productos_app.producto'),
        ),
        migrations.DeleteModel(
            name='CategoriaProducto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
