# Generated by Django 5.2.1 on 2025-05-12 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes_app', '0002_remove_producto_categoria_and_more'),
        ('marketing_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='promocion_aplicada_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_vendidos_con_esta_promocion', to='marketing_app.promocion'),
        ),
        migrations.DeleteModel(
            name='Promocion',
        ),
    ]
