# Generated by Django 5.2.1 on 2025-05-09 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito_app', '0001_initial'),
        ('productos_app', '0001_initial'),
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.cliente'),
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carrito_app.carrito'),
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos_app.producto'),
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['fecha_actualizacion'], name='carrito_fecha_a_24b9bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carritoproducto',
            unique_together={('carrito', 'producto')},
        ),
    ]
