# Generated by Django 5.2.1 on 2025-05-20 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='direccion',
            field=models.TextField(blank=True, help_text='Dirección específica de la bodega, si es diferente a la sucursal.', null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='tipo_bodega',
            field=models.CharField(choices=[('TIENDA', 'Bodega de Tienda / Punto de Venta'), ('ALMACEN', 'Bodega de Almacén Principal')], default='ALMACEN', help_text='Define si esta ubicación es para venta directa al cliente o almacenamiento.', max_length=15),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='sucursales_app.sucursal'),
        ),
    ]
