# Generated by Django 5.2.1 on 2025-05-10 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing_app', '0001_initial'),
        ('productos_app', '0001_initial'),
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientenotificacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.cliente'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['fecha_envio'], name='notificacio_fecha_e_f98f8d_idx'),
        ),
        migrations.AddField(
            model_name='clientenotificacion',
            name='notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.notificacion'),
        ),
        migrations.AddField(
            model_name='productopromocion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos_app.producto'),
        ),
        migrations.AddIndex(
            model_name='promocion',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='promocion_fecha_i_daf929_idx'),
        ),
        migrations.AddIndex(
            model_name='promocion',
            index=models.Index(fields=['activa', 'fecha_inicio', 'fecha_fin'], name='promocion_activa_04e7f0_idx'),
        ),
        migrations.AddField(
            model_name='productopromocion',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing_app.promocion'),
        ),
        migrations.AlterUniqueTogether(
            name='clientenotificacion',
            unique_together={('cliente', 'notificacion')},
        ),
        migrations.AlterUniqueTogether(
            name='productopromocion',
            unique_together={('producto', 'promocion')},
        ),
    ]
